name: I am having difficulty installing Skip or getting it to work
description: You have run into problems while downloading or installing Skip, or the "skip" tool is failing with an error.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Skip!

      If you are looking for support, please check out our documentation:

          - https://skip.tools/docs
          - https://skip.tools/docs/faq

        If you have found a bug or if our documentation doesn't have an answer
        to what you're looking for, then fill out the template below.
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/skiptools/skip/issues)
        - Read the [guide to finding help](https://skip.tools/docs/help/)
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please tell us exactly how to reproduce the problem you are running into.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Please tell us what is actually happening
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: |
        Include the full logs of the commands you are running between the lines
        with the backticks below. If you are running any `skip` commands,
        please include the output of running them with `--verbose`; for example,
        the output of running `skip create --verbose`.

        If the logs are too large to be uploaded to Github, you may upload
        them as a `txt` file or use online tools like https://pastebin.com to
        share it.

        Note: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload logs.
      value: |
        <details open>
        <summary>Logs</summary>

        ```console

        <!-- Paste your logs here -->

        ```

        </details>
  - type: textarea
    attributes:
      label: Skip Checkup output
      description: |
        Please provide the full output of running `skip checkup -v`
      value: |
        <details open>
        <summary>Checkup output</summary>

        ```console

        <!-- Paste your output here -->

        ```

        </details>
    validations:
      required: true
