blank_issues_enabled: true
contact_links:
  - name: I want help writing my application
    url: https://community.skip.tools
    about: Ask your questions about how to achieve a particular effect in Skip or get help with using a particular API.
